package GUI;

import java.text.SimpleDateFormat;
import java.util.Date;
import Common.Configuration;
import Common.FileOperations;
import Common.UserList;
import MessageClasses.Message;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 * A class for Message page of the GUI
 */
public class MessagePage extends javax.swing.JFrame {


    private String ip;
    private String port;
    private static String userId;
    private static String status;

    /**
     * Creates new form GUI.MessagePage and sets the needed variables starts a thread that refreshes the page
     */
    public MessagePage(String userid) {
        initComponents();
        UserIDLabel.setText(userid);
        userId = userid;
        ip = UserList.getIp(userid);
        port = UserList.getPort(userid);
        status = UserList.checkStatus(userid);
        new Thread(MessagePage::refreshMessagePage).start();
    }
    /***
     * Back button on click
     */
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MainPage mp = new MainPage();
        mp.setVisible(true);
        dispose();
    }
    /***
     * Send button on click
     */
    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {

        //Get the text
        String text = SendMessageArea.getText();
        //set text to empty
        SendMessageArea.setText("");
        //if user is offline
        if (status.toLowerCase().equals("offline")) {

            //get date now
            SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd-HHmmss.SSS");
            String now = sdf.format(new Date());

            //show message
            showMessageDialog(null, "The person you send message to is offline now your message will be send once they are online");

            //Write it into the offline messages file
            FileOperations.writeFile("OfflineMessages", Configuration.MessagesFolderName, now + "," + userId + "," + ip + "," + port + "," + text);
        }
        else {
            //Send the message
            Message.sendMessage(userId, ip, port, text, "text");
        }

    }
    /**
     * Refresh the message page
     *
     * */
    private static void refreshMessagePage() {
        while (true) {
            //read the sended and received messages lines in string array
            String[] sendedMessages = FileOperations.readFile(Configuration.MessagesFolderName, userId + "Send");
            String[] receivedMessages = FileOperations.readFile(Configuration.MessagesFolderName, userId + "Received");

            //join them with new line
            String send = String.join("\n", sendedMessages);
            String receive = String.join("\n", receivedMessages);

            //if they are equal dont do anything
            if (!SendMessages.getText().equals(send)) {
                //set the text to new
                SendMessages.setText(send);
                //set the caret position to bottom
                SendMessages.setCaretPosition(SendMessages.getDocument().getLength() - 1);
            }
            if (!GetMessages.getText().equals(receive)) {
                //set the text to new
                GetMessages.setText(receive);
                //set the caret position to bottom
                GetMessages.setCaretPosition(GetMessages.getDocument().getLength() - 1);

            }
            //update the status of the person
            status = UserList.checkStatus(userId);
            //set the text
            statusLabel.setText(status);
            //if it is online no last seen
            if (status.equals("online")) {
                jLabel2.setText("");
                LastSeenLabel.setText("");
            } else {
                //set last seen
                jLabel2.setText("Last Seen:");
                LastSeenLabel.setText(UserList.getLastSeen(userId));

            }
            //sleep 2,5 seconds
            try {
                Thread.sleep(2500);
            } catch (InterruptedException e) {
                // Not important
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SendMessageArea = new javax.swing.JTextArea();
        SendButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        UserIDLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LastSeenLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        GetMessages = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        SendMessages = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SendMessageArea.setColumns(20);
        SendMessageArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        SendMessageArea.setRows(5);
        jScrollPane1.setViewportView(SendMessageArea);
        SendButton.setText("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        UserIDLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserIDLabel.setText("USER ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Last Seen:");

        LastSeenLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LastSeenLabel.setText("13:53 12/10/2018");

        BackButton.setText("Go Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Status:");

        statusLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusLabel.setText("Online");

        //I have experimented and written some parts of it
        GetMessages.setColumns(20);
        GetMessages.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        GetMessages.setRows(5);
        GetMessages.setEnabled(true);
        GetMessages.setEditable(false);
        //GetMessages.setContentType("text/html");
        jScrollPane3.setViewportView(GetMessages);
        GetMessages.setLineWrap(true);
        GetMessages.setWrapStyleWord(true);

        SendMessages.setColumns(20);
        SendMessages.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        SendMessages.setRows(5);
        //SendMessages.setContentType("text/html");
        SendMessages.setEnabled(true);
        SendMessages.setEditable(false);
        jScrollPane4.setViewportView(SendMessages);
        SendMessages.setLineWrap(true);
        SendMessages.setWrapStyleWord(true);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(BackButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(UserIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(89, 89, 89)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(LastSeenLabel))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(statusLabel)))
                                                .addGap(24, 24, 24))
                                        .addComponent(jSeparator1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1)
                                                                .addGap(16, 16, 16)
                                                                .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(statusLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(LastSeenLabel)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(UserIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration
    private javax.swing.JButton BackButton;
    private static javax.swing.JTextArea GetMessages;
    private static javax.swing.JLabel LastSeenLabel;
    private javax.swing.JButton SendButton;
    private javax.swing.JTextArea SendMessageArea;
    private static javax.swing.JTextArea SendMessages;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private static javax.swing.JLabel statusLabel;
    // End of variables declaration
}
